language: scala
scala:
  - 2.12.10
  - 2.13.2
jdk:
  - openjdk8
  - openjdk11

matrix:
  exclude:
    - scala: 2.11.12
      jdk: openjdk11

script: |
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sonar-scanner

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

addons:
  sonarcloud:
    organization: "codeoncoffee" # the key of the org you chose at step #3